### ISSUE TITLE
deploying error in baobab

### ISSUE THREAD

**Issue by KwonMinho** [ontology-tech/DID-solidity#1]
I am trying to deploy the currently contract to truffle and klaytn IDE, but both cannot.
I think _**DIDcontract**_is too big, is it possible to deploy?

**Comment by qiluge** [comment]
Yes, `DIDContract` is too big, please adjust youre solc version and optimizer level.

**Comment by KwonMinho** [comment]
oh..Thank you for your answer. Modified to fit the testnet of klayth.
